version: '3.7'
services:
    postgres:
        image: postgres
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # copy the sql script to fill tables
          - ./database/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    blockchain_logger:
      container_name: filmovie
      image: filmovie-backend
      restart: on-failure
      volumes: 
        - /home/luizglomyer/Documentos/git/filmovie/backend/src:/app 
      ports: 
        - '5000:5000'
      expose:
        - "5000"
